vtk_frame_domain(
  label = "y",
  start = 0,
  end = 20000,
  interval = 15,
  flags = (Pr=1),
  dimension = 2,
  direction = y,
  position = 0,
)


vtk_frame_domain(
  label = "z500",
  start = 0,
  end = 20000,
  interval = 15,
  flags = (Pr=1),
  dimension = 2,
  direction = z,
  position = 500,
)


