!Use grid for x from file xgrid.txt?
!T...yes, F...no
F
!Use grid for y from file ygrid.txt?
!T...yes, F...no
F
!Use grid for z from file zgrid.txt?
!T...yes, F...no
F
!x(0) coordinate of W boudary
!-30
-1500
!y(0) coordinate of S boudary
!
-1500
!z(0) coordinate of B boudary
!
0
!lx
!100
5000
!ly
!4.5
5000
!lz
!
2500
!nx
!120
64
!ny
!40
64
!nz
!
32










