!compute moisture?
!0..no, 1..yes
1
!Default value of total moisture
!
0.006
!Type of Western (x min) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
3
!Type of Eastern (x max) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
3
!Type of Southern (y min) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
3
!Type of Northern (y max) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
3
!Type of Bottom (z min) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
6
!Type of Top (z max) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
6
!T on W boundary
!
0
!T on E boundary
!
0
!T on S boundary
!
0
!T on N boundary
!
0
!T on B boundary
!
0.0001
!T on T boundary
!
0
!
!
!
