bc(
  sides=[w,e,s,n,top,bottom],
  type=periodic,
)

ic(inlet_type=turbulent,
   stg=(profile="constant", u_star=0.377, Uinlet=[1,0,0], T_Lag=0.2, L_y=0.1, L_z=0.1, stress=[4.9,3.4,1.8,0,-1,0])
)



