import os
comp = ARGUMENTS.get('comp','')
prec = ARGUMENTS.get('prec','')
omp = ARGUMENTS.get('omp','')
fast = ARGUMENTS.get('fast','')
lto = ARGUMENTS.get('lto','')
prof = ARGUMENTS.get('prof','')
diag = ARGUMENTS.get('diag','')
sanitize = ARGUMENTS.get('sanitize','')
dir = ARGUMENTS.get('dir','')
customSB = ARGUMENTS.get('customSB','')
SB = ARGUMENTS.get('SB','')
customPB = ARGUMENTS.get('customPB','')
PB = ARGUMENTS.get('PB','')
extra = ARGUMENTS.get('extra','')
cgal = ARGUMENTS.get('cgal','')

extra_flag = ' ' + str(extra)

target_dir = str(dir)
if (len(target_dir)>0) and (target_dir[-1]!='/'):
  target_dir += '/'

if str(prec)=='dp':
  prec_dir = 'dp/'
  prec_flag = ' -DDPREC'
else:
  prec_dir = 'sp/'
  prec_flag = ''


if str(comp)=='intel':
  env = Environment(tools=['default','ifort','intelc'])
  
  if str(omp)!='no':
    omp_flag = ' -openmp -recursive'
  else:
    omp_flag = ''

  if str(fast)=='yes':
   fast_flag = ' -O3 -shared-intel'
  else:
   fast_flag = ' -g -debug extended -O0 -shared-intel -check all,noarg_temp_created -traceback -warn all,nounused -fstack-protector -fpe1'

  if str(lto)=='yes':
    lto_flag = ' -ipo'
  else:
    lto_flag = ''

  env.Append(F90FLAGS='-cpp -standard-semantics -heap-arrays 200')

  env.Append(LIBPATH = ['/usr/local/poisfft_intel/','/usr/local/openblas-intel/lib/'])

  env.Append(F90PATH = [target_dir,target_dir+'/P/'])

  if str(diag)=='yes':
    env.Append(F90FLAGS=' -diag-enable sc1 -diag-enable sc-precise')
    env.Append(LINKFLAGS=' -diag-enable sc1 -diag-enable sc-precise')
   
else:
  env = Environment()
 
  if str(omp)!='no':
    omp_flag = ' -fopenmp'
  else:
    omp_flag = ''

  if str(fast)=='yes':
    fast_flag = ' -Ofast'# -Warray-temporaries'
  else:
    fast_flag = ' -fcheck=all -Wall -Wsurprising -Waliasing -Wimplicit-interface -Wno-unused-dummy-argument -Wno-unused -Wno-aliasing  -Werror'
    
  if str(sanitize)=='yes':
    fast_flag += ' -fsanitize=undefined -fsanitize=address -fsanitize=unreachable -fsanitize=null -fsanitize=signed-integer-overflow'
    
  if str(lto)=='yes':
    lto_flag = ' -flto'
  else:
    lto_flag = ''

  env.Replace(F90='gfortran')
  
  env.Append(F90FLAGS='-cpp -fbacktrace -g -fstack-arrays')

  env.Append(LINKFLAGS='-static-libgcc -static-libstdc++ -static-libgfortran')

  #env.Append(LIBPATH = ['/usr/local/poisfft_gcc/'])

  env.Append(F90PATH = [target_dir,target_dir+'/P/'])#,'/usr/local/poisfft_gcc/']
  
  env.Append(FORTRANMODDIRPREFIX = '-J')
  
  
def from_env(s):
  try:
    env.Append(ENV = {s : os.environ[s]})
  except:
    pass

from_env('PATH')
from_env('LIBRARY_PATH')
from_env('LD_LIBRARY_PATH')
from_env('C_INCLUDE_PATH')
from_env('CPLUS_INCLUDE_PATH')
from_env('INTEL_LICENSE_FILE')

#HACK for some computers setting only LD_LIBRARY_PATH
try:
  env.Append(ENV = {'LIBRARY_PATH' : os.environ['LD_LIBRARY_PATH']})
except:
  pass

try:
  fc = os.environ['FC']
  if len(fc)>0:
    env.Replace(F90 = fc, FORTRAN = fc)
except:
  pass

env.Replace(LINK = env.Dump('F90'))

if prof=="yes":
  prof_flag=' -pg'
else:
  prof_flag=''
  
env.Append(F90FLAGS= fast_flag + omp_flag + prof_flag + lto_flag + extra_flag + prec_flag)# + ' -gdwarf-3'
  
env.Append(LINKFLAGS= fast_flag + omp_flag + prof_flag + lto_flag + extra_flag) # + '-Bdynamic -lpoisfft -lfftw3 -lfftw3f -lfftw3_omp -lfftw3f_omp -Bstatic -lgfortran -lquadmath -lstdc++ -llapack -L/usr/lib/x86_64-linux-uclibc/usr/lib/ -lc -lm -lpthread'  -Wl,--verbose
    
env.Append(FORTRANMODDIR = target_dir)

#instead of openblas, any blas and lapack can be used.
env.Append(LIBS = ['openblas','fftw3','fftw3f','fftw3_omp','fftw3f_omp','pthread','stdc++'])

if customSB=='yes':
 env.Append(F90FLAGS='-DCUSTOMSB')
 if str(SB)=='':
   SBfile = ['../custom/emptySB.o']
 else:
   SBfile = [str(SB)]
else:
 SBfile=[]
   
   
if customPB=='yes':
  env.Append(F90FLAGS='-DCUSTOMPB')
  if str(PB)=='':
    PBfile = ['../custom/emptyPB.o']
  else:
    PBfile = [str(PB)]
else:
  PBfile=[]


#May be used to compile PoisFFT directly, adjust the correct path.
Mkdir(target_dir+'/P/')
objs = env.Object(target=target_dir+'P/customfftw3', source='../../PoisFFT/src/customfftw3.f90')
objs += env.Object(target=target_dir+'P/precisions', source='../../PoisFFT/src/precisions.f90')
objs += env.Object(target=target_dir+'P/parameters', source='../../PoisFFT/src/parameters.f90')
objs += env.Object(target=target_dir+'P/fft', source='../../PoisFFT/src/fft.f90')
Depends(objs[-1], '../../PoisFFT/src/fft-inc.f90')
Depends(objs[-1], objs[0])
Depends(objs[-1], objs[1])
Depends(objs[-1], objs[2])
objs += env.Object(target=target_dir+'P/poisfft', source='../../PoisFFT/src/poisfft.f90')
Depends(objs[-1], '../../PoisFFT/src/poisfft-inc.f90')
Depends(objs[-1], objs[2])
objs += env.Object(target=target_dir+'P/main', source='../../PoisFFT/src/main.f90')

objs =  env.Object(target=target_dir+'parameters',     source='parameters.f90')
objs += env.Object(target=target_dir+'lapack',         source='lapack.f')
objs += env.Object(target=target_dir+'strings',        source='strings.f90')
objs += env.Object(target=target_dir+'lists',          source='lists.f90')
objs += env.Object(target=target_dir+'alternate_ieee_isnan', source='alternate_ieee_isnan.f90', F90FLAGS = filter(lambda flag: flag !='-flto',filter(lambda flag: flag !='-Ofast' , env['F90FLAGS'])))
objs += env.Object(target=target_dir+'endianness',     source='endianness.f90')
objs += env.Object(target=target_dir+'freeunit',       source='freeunit.f90')
objs += env.Object(target=target_dir+'arrayutilities', source='arrayutilities.f90')
objs += env.Object(target=target_dir+'tiling',         source='tiling.f90')
objs += env.Object(target=target_dir+'simplevtk',      source='simplevtk.f90')
objs += env.Object(target=target_dir+'limiters',       source='limiters.f90')
objs += env.Object(target=target_dir+'multigrid',      source='multigrid.f90')
objs += env.Object(target=target_dir+'multigrid2d',    source='multigrid2d.f90')
objs += env.Object(target=target_dir+'solarradiation', source='solarradiation.f90')
objs += env.Object(target=target_dir+'wallmodels',     source='wallmodels.f90', F90FLAGS = filter(lambda flag: flag !='-flto' , env['F90FLAGS']))
objs += env.Object(target=target_dir+'volumesources',  source='volumesources.f90')
objs += env.Object(target=target_dir+'linesources',    source='linesources.f90')
objs += env.Object(target=target_dir+'puffs',          source='puffs.f90')

if cgal=='no':
  #Disable support for CGAL. Useful for enabling valgrind.
  objs += env.Object(target=target_dir+'dummy_cgal_polyhedra',  source='dummy_cgal_polyhedra.f90')
else:
  #Support for CGAL for geometry files reading.
  objs += env.Object(target=target_dir+'cgal_polyhedra_cc',  source='cgal_polyhedra.cc', CXXFLAGS="-O3 -std=c++11 -frounding-math")#" -Ofast -frounding-math -std=c++11")
  objs += env.Object(target=target_dir+'cgal_polyhedra',  source='cgal_polyhedra.f90')
  Depends(objs[-1], 'cgal_polyhedra.cc')
  env.Append(LIBS = ['CGAL','boost_thread','boost_system'])
  




objs += env.Object(target=target_dir+'elevationmodels',source='elevationmodels.f90')
objs += env.Object(target=target_dir+'geometricshapes',source='geometricshapes.f90')
objs += env.Object(target=target_dir+'solidbodies',    source='solidbodies.f90')
objs += env.Object(target=target_dir+'immersedboundary',source='immersedboundary.f90')
objs += env.Object(target=target_dir+'turbinlet',      source='turbinlet.f90')
objs += env.Object(target=target_dir+'boundaries',     source='boundaries.f90')
objs += env.Object(target=target_dir+'scalarboundaries',source='scalarboundaries.f90')
objs += env.Object(target=target_dir+'scalars',        source='scalars.f90')
objs += env.Object(target=target_dir+'filters',        source='filters.f90')
objs += env.Object(target=target_dir+'subgrid',        source='subgrid.f90')
objs += env.Object(target=target_dir+'pthreadsc',      source='pthreads.c')
objs += env.Object(target=target_dir+'pthreadsf',      source='pthreads.f90')
objs += env.Object(target=target_dir+'frames_common',  source='frames_common.f90')
objs += env.Object(target=target_dir+'frames',         source='frames.f90')
objs += env.Object(target=target_dir+'output_helpers', source='output_helpers.f90')
objs += env.Object(target=target_dir+'vtkframes',      source='vtkframes.f90')
objs += env.Object(target=target_dir+'outputs',        source='outputs.f90')
objs += env.Object(target=target_dir+'poisson',        source='poisson.f90')
objs += env.Object(target=target_dir+'pressure',       source='pressure.f90')
objs += env.Object(target=target_dir+'initial',        source='initial.f90')
objs += env.Object(target=target_dir+'cds',            source='cds.f90')
objs += env.Object(target=target_dir+'tsteps',         source='tsteps.f90')
Depends(objs[-1], 'tsteps-shared.f90')
objs += env.Object(target=target_dir+'main',           source='main.f90')

objs = filter(lambda o: str(o)[-4:] != '.mod', objs)

t = env.Program(target=target_dir+'CLMM', source= objs + SBfile + PBfile + [target_dir+'P/poisfft.o'] + [target_dir+'P/fft.o'])

Default(t)
