import os
comp = ARGUMENTS.get('comp','')
prec = ARGUMENTS.get('prec','')
openmp = ARGUMENTS.get('openmp','')
fast = ARGUMENTS.get('fast','')
lto = ARGUMENTS.get('lto','')
prof = ARGUMENTS.get('prof','')
diag = ARGUMENTS.get('diag','')
sanitize = ARGUMENTS.get('sanitize','')
dir = ARGUMENTS.get('dir','')
customSB = ARGUMENTS.get('customSB','')
SB = ARGUMENTS.get('SB','')
customPB = ARGUMENTS.get('customPB','')
customPuff = ARGUMENTS.get('customPuff','')
customConfig = ARGUMENTS.get('customConfig','')
PB = ARGUMENTS.get('PB','')
extra = ARGUMENTS.get('extra','')
cgal = ARGUMENTS.get('cgal','')
mpi = ARGUMENTS.get('mpi','')

extra_flag = ' ' + str(extra)

target_dir = str(dir)
if (len(target_dir)>0) and (target_dir[-1]!='/'):
  target_dir += '/'

if str(prec)=='dp':
  prec_dir = 'dp/'
  prec_flag = ' -DDPREC'
else:
  prec_dir = 'sp/'
  prec_flag = ''
  
c_check_flag = ''


if str(comp)=='intel':
  env = Environment(tools=['default','ifort','intelc'])
  
  if str(openmp)!='no':
    openmp_flag = ' -openmp -recursive'
  else:
    openmp_flag = ' -recursive -reentrancy'

  if str(fast)=='yes':
   fast_flag = ' -O3 -shared-intel'
   check_flag = ''
  else:
   fast_flag = ' -O3'#' -g -debug extended -O0 -shared-intel -check all,noarg_temp_created -traceback -warn all,nounused -fstack-protector -fpe1'
   check_flag = ' -g -check all,noarg_temp_created -traceback'

  if str(lto)=='yes':
    lto_flag = ' -ipo'
  else:
    lto_flag = ''

  env.Append(F90FLAGS='-cpp -standard-semantics -heap-arrays 200')

  env.Append(LIBPATH = ['/usr/local/poisfft_intel/','/usr/local/openblas-intel/lib/'])

  env.Append(F90PATH = [target_dir,target_dir+'/P/'])

  if str(diag)=='yes':
    env.Append(F90FLAGS=' -diag-enable sc1 -diag-enable sc-precise')
    env.Append(LINKFLAGS=' -diag-enable sc1 -diag-enable sc-precise')
   
else:
  env = Environment()
 
  if str(openmp)!='no':
    openmp_flag = ' -fopenmp'
  else:
    openmp_flag = ' -frecursive'

  if str(fast)=='yes':
    fast_flag = '  -O5 -ffast-math -fno-protect-parens'# -Warray-temporaries'
    check_flag = '  -fbacktrace -g'
  else:
    fast_flag = ' -O5 -ffast-math -fno-protect-parens'
    c_check_flag = ' -g -Wall -Wno-unused -Wno-maybe-uninitialized'
    check_flag = c_check_flag + ' -fbacktrace -Waliasing -Wimplicit-interface -Wsurprising -Wno-unused-dummy-argument -Wno-aliasing  -fcheck=all  -Werror'

  if str(sanitize)=='yes':
    fast_flag += ' -fsanitize=address -fsanitize=undefined -fsanitize=address -fsanitize=unreachable -fsanitize=null -fsanitize=signed-integer-overflow'
    
  if str(lto)=='yes':
    lto_flag = ' -flto'
  else:
    lto_flag = ''

  env.Replace(F90='gfortran')
  
  env.Append(F90FLAGS='-cpp')#-fstack-arrays

  env.Append(LINKFLAGS='-static-libgcc -static-libstdc++ -static-libgfortran')

  #env.Append(LIBPATH = ['/usr/local/poisfft_gcc/'])

  env.Append(F90PATH = [target_dir,target_dir+'/P/'])#,'/usr/local/poisfft_gcc/']
  
  env.Append(FORTRANMODDIRPREFIX = '-J')
  
  
def from_env(s):
  try:
    env.Append(ENV = {s : os.environ[s]})
  except:
    pass

from_env('PATH')
from_env('LIBRARY_PATH')
from_env('LD_LIBRARY_PATH')
from_env('C_INCLUDE_PATH')
from_env('CPATH')
from_env('CPLUS_INCLUDE_PATH')
from_env('INTEL_LICENSE_FILE')

#HACK for some computers setting only LD_LIBRARY_PATH
try:
  env.Append(ENV = {'LIBRARY_PATH' : os.environ['LD_LIBRARY_PATH']})
except:
  pass

try:
  fc = os.environ['FC']
  if len(fc)>0:
    env.Replace(F90 = fc, FORTRAN = fc)
except:
  pass

env.Replace(LINK = env.Dump('F90'))

if prof=="yes":
  prof_flag=' -pg'
else:
  prof_flag=''
  
env.Append(F90FLAGS= fast_flag + openmp_flag + prof_flag + lto_flag + extra_flag + prec_flag + check_flag)
env.Append(FFLAGS= env['F90FLAGS'])
env.Append(CFLAGS= ' -O3 '+ openmp_flag + prof_flag + lto_flag + extra_flag + prec_flag + c_check_flag)
env.Append(CXXFLAGS= ' -O3 ' + openmp_flag + prof_flag + extra_flag + prec_flag + c_check_flag)
  
env.Append(LINKFLAGS= fast_flag + openmp_flag + prof_flag + lto_flag + extra_flag) # + '-Bdynamic -lpoisfft -lfftw3 -lfftw3f -lfftw3_omp -lfftw3f_omp -Bstatic -lgfortran -lquadmath -lstdc++ -llapack -L/usr/lib/x86_64-linux-uclibc/usr/lib/ -lc -lm -lpthread'  -Wl,--verbose
    
env.Append(FORTRANMODDIR = target_dir)

if str(mpi)=='yes':
  env.Replace(LINK = 'mpif90')
  env.Replace(F90 = 'mpif90')
  env.Replace(CC = 'mpicc')
  env.Replace(CXX = 'mpic++')
  env.Append(F90FLAGS=' -DMPI')
  env.Append(CFLAGS=' -DMPI')
  env.Append(CXXFLAGS=' -DMPI')
  env.Append(LIBS = ['pfft','pfftf','fftw3_mpi','fftw3f_mpi'])

#instead of openblas, any blas and lapack can be used.
env.Append(LIBS = ['blas','lapack','fftw3','fftw3f','pthread','stdc++'])
if str(openmp)!='no':
  env.Append(LIBS = ['fftw3_omp','fftw3f_omp'])

if customSB=='yes':
 env.Append(F90FLAGS='-DCUSTOMSB')
 if str(SB)=='':
   SBfile = ['../custom/emptySB.f90']
 else:
   SBfile = [str(SB)]
else:
 SBfile=[]
   
   
if customPB=='yes':
  env.Append(F90FLAGS='-DCUSTOMPB')
  if str(PB)=='':
    PBfile = ['../custom/emptyPB.f90']
  else:
    PBfile = [str(PB)]
else:
  PBfile=[]
  
if customPuff=='yes':
  env.Append(F90FLAGS='-DCUSTOM_PUFF_SOURCES')
  
if customConfig=='yes':
  env.Append(F90FLAGS='-DCUSTOM_CONFIG')

#May be used to compile PoisFFT directly, adjust the correct path.
Mkdir(target_dir+'/P/')
objs = env.Object(target=target_dir+'P/customfftw3', source='../../PoisFFT/src/customfftw3.f90')
if str(mpi)=='yes':
  objs += env.Object(target=target_dir+'P/missing_pfft', source='../../PoisFFT/src/missing_pfft.c')
  objs += env.Object(target=target_dir+'P/custompfft', source='../../PoisFFT/src/custompfft.f90')
objs += env.Object(target=target_dir+'P/precisions', source='../../PoisFFT/src/precisions.f90')
objs += env.Object(target=target_dir+'P/parameters', source='../../PoisFFT/src/parameters.f90')
objs += env.Object(target=target_dir+'P/fft', source='../../PoisFFT/src/fft.f90', F90FLAGS = filter(lambda flag: flag !='-ipo' , env['F90FLAGS']))
Depends(objs[-1], '../../PoisFFT/src/fft-inc.f90')
Depends(objs[-1], '../../PoisFFT/src/plan_new-inc.f90')
Depends(objs[-1], '../../PoisFFT/src/allocate_fftw-inc.f90')
Depends(objs[-1], objs[0])
Depends(objs[-1], objs[2])
Depends(objs[-1], objs[3])
objs += env.Object(target=target_dir+'P/poisfft', source='../../PoisFFT/src/poisfft.f90')
Depends(objs[-1], '../../PoisFFT/src/poisfft-inc.f90')
Depends(objs[-1], '../../PoisFFT/src/poisfft-solvers-inc.f90')
Depends(objs[-1], '../../PoisFFT/src/loop_nest_3d.f90')
Depends(objs[-1], objs[3])
objs += env.Object(target=target_dir+'P/main', source='../../PoisFFT/src/main.f90')

if str(mpi)=='yes':
  objs += env.Object(target=target_dir+'custom_mpi',        source='custom_mpi.f90')
  objs += env.Object(target=target_dir+'exchange_mpi',      source='exchange_mpi.f90')


objs += env.Object(target=target_dir+'parameters',     source='parameters.f90')
objs += env.Object(target=target_dir+'rng_par_zig',    source='rng_par_zig.f90')
objs += env.Object(target=target_dir+'stop',           source='stop.f90')
objs += env.Object(target=target_dir+'lapack',         source='lapack.f')
objs += env.Object(target=target_dir+'strings',        source='strings.f90')
objs += env.Object(target=target_dir+'lists',          source='lists.f90')
objs += env.Object(target=target_dir+'alternate_ieee_isnan', source='alternate_ieee_isnan.f90', F90FLAGS = filter(lambda flag: flag !='-flto',filter(lambda flag: flag !='-Ofast' , env['F90FLAGS'])))
objs += env.Object(target=target_dir+'endianness',     source='endianness.f90')
objs += env.Object(target=target_dir+'freeunit',       source='freeunit.f90')
objs += env.Object(target=target_dir+'arrayutilities', source='arrayutilities.f90')
objs += env.Object(target=target_dir+'tiling',         source='tiling.f90')
objs += env.Object(target=target_dir+'simplevtk',      source='simplevtk.f90')
objs += env.Object(target=target_dir+'limiters',       source='limiters.f90')
objs += env.Object(target=target_dir+'multigrid',      source='multigrid.f90')
objs += env.Object(target=target_dir+'multigrid2d',    source='multigrid2d.f90')
objs += env.Object(target=target_dir+'solarradiation', source='solarradiation.f90')
objs += env.Object(target=target_dir+'wallmodels',     source='wallmodels.f90', F90FLAGS = filter(lambda flag: flag !='-flto' , env['F90FLAGS']))
objs += env.Object(target=target_dir+'volumesources',  source='volumesources.f90')
objs += env.Object(target=target_dir+'linesources',    source='linesources.f90')
objs += env.Object(target=target_dir+'pointsources',   source='pointsources.f90')
objs += env.Object(target=target_dir+'puffs',          source='puffs.f90')

if cgal=='no':
  #Disable support for CGAL. Useful for enabling valgrind.
  objs += env.Object(target=target_dir+'dummy_cgal_polyhedra',  source='dummy_cgal_polyhedra.f90')
else:
  #Support for CGAL for geometry files reading.
  objs += env.Object(target=target_dir+'cgal_polyhedra_cc',  source='cgal_polyhedra.cc', CXXFLAGS = env['CXXFLAGS'] + '-O3 -std=c++11 -frounding-math')
  objs += env.Object(target=target_dir+'cgal_polyhedra',  source='cgal_polyhedra.f90')
  Depends(objs[-1], 'cgal_polyhedra.cc')
  env.Append(LIBS = ['CGAL','boost_thread','boost_system'])
  




objs += env.Object(target=target_dir+'elevationmodels',source='elevationmodels.f90')
objs += env.Object(target=target_dir+'geometricshapes',source='geometricshapes.f90')
objs += env.Object(target=target_dir+'solidbodies',    source='solidbodies.f90')
objs += env.Object(target=target_dir+'immersedboundary',source='immersedboundary.f90')
objs += env.Object(target=target_dir+'turbinlet',      source='turbinlet.f90')
objs += env.Object(target=target_dir+'boundaries',     source='boundaries.f90')
objs += env.Object(target=target_dir+'scalarboundaries',source='scalarboundaries.f90')
objs += env.Object(target=target_dir+'scalars',        source='scalars.f90')
objs += env.Object(target=target_dir+'filters',        source='filters.f90')
objs += env.Object(target=target_dir+'subgrid',        source='subgrid.f90')
objs += env.Object(target=target_dir+'pthreadsc',      source='pthreads.c')
objs += env.Object(target=target_dir+'pthreadsf',      source='pthreads.f90')
objs += env.Object(target=target_dir+'frames_common',  source='frames_common.f90')
objs += env.Object(target=target_dir+'frames',         source='frames.f90')
objs += env.Object(target=target_dir+'output_helpers', source='output_helpers.f90')
objs += env.Object(target=target_dir+'vtkframes',      source='vtkframes.f90')
objs += env.Object(target=target_dir+'surfacemapframes',      source='surfacemapframes.f90')
objs += env.Object(target=target_dir+'outputs',        source='outputs.f90')
objs += env.Object(target=target_dir+'poisson',        source='poisson.f90')
objs += env.Object(target=target_dir+'pressure',       source='pressure.f90')
objs += env.Object(target=target_dir+'initial',        source='initial.f90')
objs += env.Object(target=target_dir+'cds',            source='cds.f90')
objs += env.Object(target=target_dir+'tsteps',         source='tsteps.f90')
Depends(objs[-1], 'tsteps-shared.f90')
objs += env.Object(target=target_dir+'main',           source='main.f90')

objs = filter(lambda o: str(o)[-4:] != '.mod', objs)

t = env.Program(target=target_dir+'CLMM', source= objs + SBfile + PBfile)

Default(t)
