!Number of frames (<=0 for no frames)
!
101
!time of first frame
!
000
!time of last frame
!
1000
! Save velocity in the frames?
! 0.. no, 1.. yes
1
! Save vorticity in the frames?
! 0.. no, 1.. yes
0
! Save pressure in the frames?
! 0.. no, 1.. yes
0
! Save lambda2 in the frames?
! 0.. no, 1.. yes
0
! Save individual scalars in the frames?
! 0.. no, 1.. yes
1
! Save sum of scalars in the frames?
! 0.. no, 1.. yes
0
! Save temperature in the frames?
! 0.. no, 1.. yes
1
! Save total specific humidity q_t in the frames?
! 0.. no, 1..yes
1
! Save vertical temperature flux in the frames?
!
0
! Save vertical scalar flux in the frames?
!
0
!How many different domains save in each frame step?
!
4
!Dimension of domain 1 (full 3d or 2d slices)
!3 .. 3D, 2.. 2D slice
2
!Slice of which constant coordinate?
!1.. x, 2.. y, 3.. z
2
!Value of constant coordinate.
!
0
!Dimension of domain 2 (full 3d or 2d slices)
!3 .. 3D, 2.. 2D slice
2
!Slice of which constant coordinate?
!1.. x, 2.. y, 3.. z
3
!Value of constant coordinate.
!
0.5
!Dimension of domain 3 (full 3d or 2d slices)
!3 .. 3D, 2.. 2D slice
2
!Slice of which constant coordinate?
!1.. x, 2.. y, 3.. z
3
!Value of constant coordinate.
!
1.5
!Dimension of domain 4 (full 3d or 2d slices)
!3 .. 3D, 2.. 2D slice
2
!Slice of which constant coordinate?
!1.. x, 2.. y, 3.. z
2
!Value of constant coordinate.
!
-1.5
