!level of multigrid, Prnx=bnx*2**level,Prny=bny*2**level,for periodic BC
!for other BSs Prnx=bnx*2**level+1
4
!innermost multigrid level computed by normal Gauss-Seiel
!should be 0 or 1, optimum depends on bn's below
0
!base cell for multigrid -- bnx
!
16
!bny
!
16
!bnz
!
2
!type of mg cycling
!1.. V cycle, 2..W cycle,...
2
!number of Gauss-Seidel sweeps before recursive CGC call
!
2
!number of Gauss-Seidel sweeps after recursive CGC call
!
1
!max number of Gauss-Seidel iterations in the innermost MG level divided by 10
!
0
!epsilon for stopping GS iterations in the innermost MG level
!
1E-6
!minumum MG level yet to be computed on GPU
!
3





