!randomize initial profile? 1..yes, 0..no
!
1
!to which height randomize? in m
!
200
!amplitude of random fluctuations in K
!
0.5
!number of temperature profile sections
!
2
!top of section 1 in m
!
1000
!potential temperature at z=0, if < 0 , temperature_ref will be used
!
270.15
!potential temperature gradient in setion 1 in K/m
!
0.0
!top of section 2 in m
!
2500
!potential temperature jump at section 2 bottom in K
!
0.45
!potential temperature gradient in setion 2 in K/m
!
0.003
!top of section 2 in m
!
1500
!potential temperature jump at section 2 bottom in K
!
2
!potential temperature gradient in setion 2 in K/m
!
0.01
