!compute buoyancy?
!0..no, 1..yes
0
!Prandtl number
!0.7 for air
0.7
!gravitational acceleration
!9.81
9.81
!reference temperature
!
275.15
!Type of Western (x min) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
5
!Type of Eastern (x max) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
5
!Type of Southern (y min) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
3
!Type of Northern (y max) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
3
!Type of Bottom (z min) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
6
!Type of Top (z max) boundary
!3..periodic,4..dirichlet, 5..neumann,6..constant flux
5
!T on W boundary
!
00
!T on E boundary
!
00
!T on S boundary
!
00
!T on N boundary
!
00
!T on B boundary
!
0.002
!T on T boundary
!
0.003
!
!
!
